<?php
declare(strict_types=1);
require_once __DIR__ . '/../app/bootstrap.php';
require_once __DIR__ . '/../app/stories.php';
security_headers();
if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'GET') { header('Allow: GET'); http_response_code(405); exit('Methode nicht erlaubt.'); }
try {
    $statement = database()->prepare("SELECT title, slug, excerpt, image_url, published_at FROM stories WHERE status = 'published' AND published_at IS NOT NULL AND published_at <= UTC_TIMESTAMP() ORDER BY published_at DESC");
    $statement->execute(); $stories = $statement->fetchAll();
} catch (Throwable $exception) { error_log('Public story list failed: ' . $exception->getMessage()); $stories = []; }
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="NEMA Stories — Bilder, Filme und Erzählungen."><title>Stories — NEMA</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="/styles/style.css"><link rel="stylesheet" href="/styles/stories.css"></head><body><div class="page-shell stories-shell"><header class="site-header"><nav class="main-nav" aria-label="Hauptnavigation"><a class="nav-link" href="/">Home</a><a class="nav-link" href="/sites/kunst.html">Kunst</a><a class="nav-link" href="/sites/ai-me.html">AI &amp; Me</a><a class="nav-link active" href="/stories/" aria-current="page">Stories</a></nav></header><main><section class="stories-intro"><p class="eyebrow">NEMA / 03</p><h1>STORIES</h1><p>Images, films and narratives</p></section><section class="story-grid" aria-label="Veröffentlichte Stories"><?php if (!$stories): ?><p class="stories-empty">Bald erscheinen hier neue Stories.</p><?php endif; ?><?php foreach ($stories as $story): ?><article class="story-card"><?php if ($story['image_url']): ?><a href="/stories/story.php?slug=<?= rawurlencode($story['slug']) ?>"><img src="<?= e($story['image_url']) ?>" alt="" loading="lazy"></a><?php endif; ?><time datetime="<?= e(substr($story['published_at'], 0, 10)) ?>"><?= e((new DateTimeImmutable($story['published_at']))->format('d.m.Y')) ?></time><h2><a href="/stories/story.php?slug=<?= rawurlencode($story['slug']) ?>"><?= e(story_plain_text($story['title'])) ?></a></h2><?php if ($story['excerpt']): ?><div class="story-card-excerpt"><?= sanitize_story_html($story['excerpt']) ?></div><?php endif; ?><a class="story-read" href="/stories/story.php?slug=<?= rawurlencode($story['slug']) ?>">Lesen →</a></article><?php endforeach; ?></section></main></div></body></html>
